# Stage 1: Build the application
FROM node:22.12.0-alpine AS builder

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable pnpm && pnpm install

COPY prisma ./prisma

RUN npx prisma generate || true

COPY . .

RUN pnpm run build

# Stage 2: Create the production image
FROM node:22.12.0-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist

COPY package.json pnpm-lock.yaml ./

RUN corepack enable pnpm && pnpm install

# CMD ["node", "dist/main"]