apiVersion: v1
kind: PersistentVolume
metadata:
  name: collaboration-db-pv
spec:
  capacity:
    storage: "128Mi"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/collaboration-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collaboration-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
